version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: geniusGame_postgres
    environment:
      POSTGRES_DB: geniusGame
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - '5430:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: